dist: trusty
sudo: required
language: java

before_install:
 - sudo apt-add-repository ppa:wpilib/toolchain -y
 - sudo apt-get update -q
install:
 - sudo apt-get install frc-toolchain -y
# Skip gradlew assemble since build is a superset

script:
 - ./gradlew build
 - du -sh Pathfinder-*
 - ls Pathfinder-Core/build
 - ls Pathfinder-Java/build
 - zip -9 -r built_core Pathfinder-Core/build/libs/pathfinder
 - zip -9 -r built_java Pathfinder-Java/build/libs

# Taken from docs but with additions
before_cache:
 - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
 - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
 - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
 - openssl aes-256-cbc -iv $iv_hex -K $key_hex -in upload_key_encrypted -out upload_key -d
 - rm upload_key
