dist: trusty
sudo: required
language: java

before_install:
 - sudo apt-add-repository ppa:wpilib/toolchain -y
 - sudo apt-get update -q
 - sudo apt-get install frc-toolchain -y
script:
 - ./gradlew build
 - du -sh Pathfinder-*
 - ls Pathfinder-Core/build
 - ls Pathfinder-Java/build

 # Taken from docs

before_cache:
 - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
