install:
 - choco install winscp

build_script:
 - gradlew.bat --no-daemon build
 - echo %PATH%

after_build:
 - 7z a built_java.zip Pathfinder-Java/build/libs
 - 7z a built_core.zip Pathfinder-Core/build/libs/pathfinder
 - ps: certUtil -hashfile built_java.zip SHA256 > sha256sums
 - ps: certUtil -hashfile built_core.zip SHA256 >> sha256sums
 - type sha256sums
 - del /F C:\Users\appveyor\.gradle\caches\modules-2\modules-2.lock
 - rmdir /S /Q C:\Users\appveyor\.gradle\caches\*\plugin-resolution\
 - del /F /Q C:\Users\appveyor\.gradle\caches\*\fileHashes\fileHashes.bin
 - del /F /Q C:\Users\appveyor\.gradle\caches\*\fileHashes\fileHashes.lock

cache:
 - C:\Users\appveyor\.gradle\caches
 - C:\Users\appveyor\.gradle\wrappers

skip_commits:
  message: \[((skip ci)|(ci skip))\] 
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

artifacts:
 - path: built_core.zip
 - path: built_java.zip
 - path: sha256sums

