install:
 - choco install winscp

build_script:
 - gradlew.bat --no-daemon build
 - 7z a built_java.zip Pathfinder-Java/build/libs
 - 7z a built_core.zip Pathfinder-Core/build/libs/pathfinder
 - ps: certUtil -hashfile built_java.zip SHA256 > sha256sums
 - ps: certUtil -hashfile built_core.zip SHA256 > sha256sums
 - type sha256sums

cache:
 - C:\Users\appveyor\.gradle

skip_commits:
  message: \[((skip ci)|(ci skip))\] 
environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

artifacts:
 - path: built_core.zip
 - path: built_java.zip
 - path: sha256sums

